### ISSUE TITLE
Windows 10 64bit

### ISSUE THREAD

**Issue by Stordia** [koel/app#16]
C:\KOEL>npm run release

> @ release C:\KOEL
> gulp release --env=production

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
C:\KOEL\node_modules\gulp-util\node_modules\array-differ\index.js:2
module.exports = (arr, ...values) => {
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\KOEL\node_modules\gulp-util\lib\PluginError.js:2:19)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
 npm ERR! weird error 1
npm ERR! not ok code 0

C:\KOEL>

Anyone can help with this is appreciated ?

**Comment by DubStepMad** [comment]
Just done this on my system and works as intended.
