### ISSUE TITLE
Compilation on Windows 10 x64 fails

### ISSUE THREAD

**Issue by vmario89** [koel/app#36]
Hi, i am trying to create the electron desktop app for a while now but i come not the the end because i get a lot of errors.

What i did so far:

Edit Windows environment and add to %PATH%
- git
- nodejs (https://nodejs.org/en/download)
- C:\Python2.7
- C:\Python2.7\Scripts

The version i use:

- node-gyp v.3.8.0
- nodejs 12.14.0 LTS x64
- Python 2.7.15

create file **python2.cmd** inside C:\Python2.7 which contains "C:\Python27\python.exe" %

Start Cmder or CMD Shell
Now in the shell:

```
cd C:\
git clone --recursive https://github.com/phanan/koel-app.git
cd koel-app
npm install -g node-gyp@latest
npm install -g yarn@latest
npm config set python python2.7
npm config set msvs_version 2017
# this takes about 3-5 minutes ...
npm install --global --production windows-build-tools --vs2017
rm package-lock.json
.\node_modules\.bin\yarn
npm -g --unsafe-perm install node-sass
```

This fails with
```
"C:\koel-app\node_modules\node-sass\build\binding.sln" (Standardziel) (1) ->
"C:\koel-app\node_modules\node-sass\build\binding.vcxproj.metaproj" (Standardziel) (2) ->
"C:\koel-app\node_modules\node-sass\build\binding.vcxproj" (Standardziel) (4) ->
(ClCompile Ziel) ->
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\custom_function_bridge.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\create_string.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\custom_function_bridge.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\create_string.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\binding.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\binding.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\custom_importer_bridge.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\custom_importer_bridge.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\node-sass\src\create_string.cpp(17): error C2664: "v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)" : Konvertierung von Argument 1 von "v8::Local<v8::Value>" in "const v8::String::Utf8Value &" nicht m�glich [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\boolean.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\boolean.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_context_wrapper.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\color.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\color.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\error.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\error.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\list.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\list.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\factory.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\factory.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\map.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\map.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\null.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\null.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\string.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\string.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\sass_types\number.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_implementation_12_inl.h(356): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\sass_types\number.cpp) [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]
  c:\koel-app\node_modules\nan\nan_object_wrap.h(127): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [C:\koel-app\node_modules\node-sass\build\binding.vcxproj]

    34 Warnung(en)
    55 Fehler

Verstrichene Zeit 00:00:41.83
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\koel-app\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\koel-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\koel-app\node_modules\node-sass
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

i tried more recent NodeJS v13 as well as trying to use MSVS 2015/2019 switches. Anybody an idea on how to get it working?

regards, Mario

ps: at the documentation it's missing how the compiled Desktop application will look a like. Because in readme there you mention some OS-specific stuff. I guess there are some more buttons/views?

**Comment by vmario89** [comment]
okay figured out that nodejs 12 and 13 are too new. Used node-v11.14.0-x64.msi and now the step "yarn" successfully passed.

**Comment by vmario89** [comment]
nice, finally it compiled to a usable setup installation file
![grafik](https://user-images.githubusercontent.com/5631071/71521758-5c911580-28c2-11ea-8cc6-5cd1041fe63a.png)

![grafik](https://user-images.githubusercontent.com/5631071/71521754-5864f800-28c2-11ea-922b-0023e063be64.png)

**Comment by vmario89** [comment]
i made a small pdf documentation out of it :-)

[FCI-KoelWindowsApplication-271219-1615-8.pdf](https://github.com/koel/app/files/4005626/FCI-KoelWindowsApplication-271219-1615-8.pdf)

**Comment by phanan** [comment]
Glad you solved it!

**Comment by vmario89** [comment]
added ready to download installer for Windows 64 Bit: https://cloud.leyghis.de/d/47539a1682fe40a18472/?p=%2F&mode=list

**Comment by deadnessking** [comment]
> added ready to download installer for Windows 64 Bit: [https](https://cloud.leyghis.de/d/47539a1682fe40a18472/?p=%2F&mode=list) : [//cloud.leyghis.de/d/47539a1682fe40a18472/?p=%2F&mode=list](https://cloud.leyghis.de/d/47539a1682fe40a18472/?p=%2F&mode=list)

The link is outdate,can you provide a new one?Thanks a lot

**Comment by vmario89** [comment]
hi,
sorry for that. you can find what you are looking for, at https://cloud.leyghis.de/d/2655cd771d9649d18ba9/ or if you navigate to "Compiler Kitchen"
![grafik](https://user-images.githubusercontent.com/5631071/79726875-c6a74d80-82eb-11ea-8a1b-f8fb232fb5a5.png)

**Comment by deadnessking** [comment]
> hi,
> sorry for that. you can find what you are looking for, at https://cloud.leyghis.de/d/2655cd771d9649d18ba9/ or if you navigate to "Compiler Kitchen"
> ![grafik](https://user-images.githubusercontent.com/5631071/79726875-c6a74d80-82eb-11ea-8a1b-f8fb232fb5a5.png)

really thanks a lot

**Comment by vmario89** [comment]
i loaded up a new setup file for commit https://github.com/koel/koel/commit/b1aad4891904d8c52e325c807de72cd8cc2a3bde
